### ISSUE TITLE
Send invitation email to clients

### ISSUE THREAD

**Issue by rubenbuisman** [ConnectWeather/Documentations#3]
The invitation email must be send to the both clients to invite and inform them.

- J. Wempe
- J. Bos

**Comment by RobinMeles** [comment]
Issue closed based on the fact that we got feedback and changed our email. This is the final invitation letter: 

> Dear Mr. Bos and Mrs .Wempe,
> 
> Thank you for visiting the meeting that we conducted on the 9th of January. It was a pleasure to meet you and we as ConnectWeather enjoyed having you as our guests. We hope you feel the same way.
> 
> We would be honoured to invite you to a second meeting, located at Van Doorenveste, on the 6th of February at 14:30 (CEST) in room EM/D021. During this meeting we would like to give a full demonstration of the application we have built based on your wishes that we discussed in the first meeting.
> 
> If you would be so kind to please send us an email confirming whether you will be attending the meeting. We are looking forward to see you again and present you our application.
> 
> 
> Yours sincerely,
> 
> Koen Hendriks - CEO
> Ruben Buisman - Senior ICT Services
> Cyriel Zeilstra - Senior Development & Maintenance
> Robin Meles - Senior Data Acquisition
> Joey Boum Bletterman - Senior Service Management
